name: Build backend image

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  docker-build:
    name: Build Docker image and deploy app
    runs-on: ubuntu-20.04
    steps:
      - name: Git clone
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            registry.digitalocean.com/rezaetezal/permutate
          tags: |
            type=semver,pattern={{version}}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        id: install-doctl
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DigitalOcean Container Registry
        id: login-do
        run: doctl registry login --expiry-seconds 600

      - name: Build, then Push to registries
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Display image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
